spring.application.name: bookhive-data-loader

datadump.location:
  author: ol_dump_authors_2023-03-31.txt
  works: ol_dump_works_2023-03-31.txt


spring:
  main:
    allow-circular-references: true
  cassandra:
    keyspace-name: main
    username: nZidUEICZjeXBFBuXsAUsYlj
    password: wQn15Guc1-KXh4-Zu9P2BOJju.83_4JG7KQ3vyh2pEL9x7d8XzsO-zYRLv,GA3wGcTWEHK0+ngqxu6LjKedS.7BU-W10ayfNWRpWCfnLI8RbBgCTSB1.tJZQZKjd5hYS
    schema-action: create-if-not-exists
    request:
      timeout: 10s
    connection:
      connect-timeout: 10s
      init-query-timeout: 10s

datastax.astra:
    secure-connect-bundle: secure-connect-bookhive.zip

astra.db:
    id: 5d230668-c663-40e5-802c-9ca6f5f369ba-1
    region: asia-south1 
    keyspace: main
    application.token: AstraCS:nZidUEICZjeXBFBuXsAUsYlj:79baff842b654739771519a650cac317afbecf1888dc9ed958911f9d82a7549c